# Generated by Django 4.0.1 on 2022-02-16 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='matriculas',
        ),
    ]
